FROM msaraiva/elixir-dev:1.0.5

RUN apk --update add gcc make libc-dev libgcc zsh vim erlang-eunit && rm -rf /var/cache/apk/*
RUN mix local.hex --force && mix local.rebar --force

WORKDIR /build
COPY . /build

CMD ["make", "-f", "package/Makefile"]
