#!/bin/sh
CURRENT_DIR=$(cd ${0%/*} && pwd -P)
APP_DIR=$CURRENT_DIR/../app

get_info() {
  cd $APP_DIR && \
    mix run \
      --no-compile \
      --no-deps-check \
      --no-start \
      -r $CURRENT_DIR/app_info.exs \
      -e "IO.puts AppInfo.${1}"
}

case $1 in
  name|version|exrm)
    get_info $1
    ;;
esac
# ret=$?
