include package/shared.mk

DOCKER_IMPORT    = docker import
IMAGE_NAME       = local-release/$(APPNAME)
RELEASE_SETTINGS = --change 'CMD trap exit TERM; /app/bin/$(APPNAME) foreground & wait'

all: build

build:
	cat $(ROOTFS_TARBALL) | \
	$(DOCKER_IMPORT) $(RELEASE_SETTINGS) - $(IMAGE_NAME)
